import { afterEach, describe, it, expect, vi } from "vitest";
import { SkeletonChunk } from "#src/skeleton/backend.js";
import {
  decodeSwcSkeletonChunk,
  SwcValidation,
} from "#src/skeleton/decode_swc_skeleton.js";

const swcStr =
  "# Generated by NeuTu (https://github.com/janelia-flyem/NeuTu)\n\
# http://emdata1:7000/api/node/d5053e99753848e599a641925aa2d38f/bodies1104_skeletons/key/229802_swc\n\
1 0 4145 3191 3575 2 -1\n\
2 0 4149 3195 3579 3.65685 1\n\
3 0 4157 3195 3583 6.94427 2\n\
4 0 4161 3195 3591 3.65685 3\n\
5 0 4165 3199 3595 2 4\n";

describe("skeleton/decode_swc_skeleton", () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("decodes simple line skeleton", () => {
    const chunk = new SkeletonChunk();
    decodeSwcSkeletonChunk(chunk, swcStr, { validation: SwcValidation.STRICT });

    expect(chunk.vertexPositions).toEqual(
      new Float32Array([
        4145, 3191, 3575, 4149, 3195, 3579, 4157, 3195, 3583, 4161, 3195, 3591,
        4165, 3199, 3595,
      ]),
    ); // vertex locations
    expect(chunk.indices).toEqual(new Uint32Array([1, 0, 2, 1, 3, 2, 4, 3])); // pairs of indices for each line
  });
  it("fails parsing improper skeleton", () => {
    const chunk = new SkeletonChunk();
    const improperSwc = "# test poorly-formatted swc data 1 2 3 4 5 6";
    expect(() => {
      decodeSwcSkeletonChunk(chunk, improperSwc, {
        validation: SwcValidation.STRICT,
      });
    }).toThrow();
  });
  it("gives each node its radius and type as vertex attributes", () => {
    const chunk = new SkeletonChunk();
    decodeSwcSkeletonChunk(chunk, "1 1 0 0 0 5.5 -1\n2 3 1 0 0 0.25 1\n", {
      validation: SwcValidation.STRICT,
    });
    expect(chunk.vertexAttributes).toEqual([
      new Float32Array([5.5, 0.25]),
      new Float32Array([1, 3]),
    ]);
  });
  it("rejects a node whose parent is not in the file", () => {
    const chunk = new SkeletonChunk();
    expect(() =>
      decodeSwcSkeletonChunk(chunk, "1 1 0 0 0 1 -1\n2 3 1 0 0 1 7\n", {
        validation: SwcValidation.STRICT,
      }),
    ).toThrow("SWC node 2 has parent 7, which is not in the file");
  });
  it("decodes a file with Windows line endings", () => {
    const chunk = new SkeletonChunk();
    decodeSwcSkeletonChunk(
      chunk,
      "# header\r\n1 1 0 0 0 1 -1\r\n2 3 1 2 3 1 1\r\n",
      { validation: SwcValidation.STRICT },
    );
    expect(chunk.vertexPositions).toEqual(new Float32Array([0, 0, 0, 1, 2, 3]));
    expect(chunk.indices).toEqual(new Uint32Array([1, 0]));
  });
  it("decodes coordinates written in scientific notation", () => {
    const chunk = new SkeletonChunk();
    decodeSwcSkeletonChunk(chunk, "1 1 1.5e2 -2E-1 +3 1e0 -1\n", {
      validation: SwcValidation.STRICT,
    });
    expect(chunk.vertexPositions).toEqual(new Float32Array([150, -0.2, 3]));
    expect(chunk.vertexAttributes![0]).toEqual(new Float32Array([1]));
  });
  it("in lenient mode, skips bad lines with one warning and draws the rest of the skeleton", () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    const chunk = new SkeletonChunk();
    decodeSwcSkeletonChunk(
      chunk,
      "1 1 0 0 0 1 -1\nnot a node\n2 3 1 0 0 1 7\n3 3 2 0 0 1 1\n",
      { validation: SwcValidation.LENIENT },
    );
    expect(chunk.vertexPositions).toEqual(
      new Float32Array([0, 0, 0, 1, 0, 0, 2, 0, 0]),
    );
    expect(chunk.indices).toEqual(new Uint32Array([2, 0]));
    expect(warn).toHaveBeenCalledTimes(1);
  });
});
